{"created": 1755426984.4454975, "duration": 38.27642822265625, "exitcode": 0, "root": "/home/jclee/app/blacklist", "environment": {}, "summary": {"passed": 15, "total": 15, "collected": 15}, "collectors": [{"nodeid": "", "outcome": "passed", "result": [{"nodeid": "tests/test_collection_regtech.py", "type": "Module"}]}, {"nodeid": "tests/test_collection_regtech.py::TestRegtechCollector", "outcome": "passed", "result": [{"nodeid": "tests/test_collection_regtech.py::TestRegtechCollector::test_login_success", "type": "Function", "lineno": 45}, {"nodeid": "tests/test_collection_regtech.py::TestRegtechCollector::test_login_failure", "type": "Function", "lineno": 69}, {"nodeid": "tests/test_collection_regtech.py::TestRegtechCollector::test_data_collection_success", "type": "Function", "lineno": 94}, {"nodeid": "tests/test_collection_regtech.py::TestRegtechCollector::test_html_parsing", "type": "Function", "lineno": 125}, {"nodeid": "tests/test_collection_regtech.py::TestRegtechCollector::test_invalid_html_parsing", "type": "Function", "lineno": 153}, {"nodeid": "tests/test_collection_regtech.py::TestRegtechCollector::test_missing_table_elements", "type": "Function", "lineno": 160}, {"nodeid": "tests/test_collection_regtech.py::TestRegtechCollector::test_duplicate_removal", "type": "Function", "lineno": 170}, {"nodeid": "tests/test_collection_regtech.py::TestRegtechCollector::test_ip_address_validation", "type": "Function", "lineno": 186}, {"nodeid": "tests/test_collection_regtech.py::TestRegtechCollector::test_full_collection_process", "type": "Function", "lineno": 203}, {"nodeid": "tests/test_collection_regtech.py::TestRegtechCollector::test_error_handling_network_failure", "type": "Function", "lineno": 237}, {"nodeid": "tests/test_collection_regtech.py::TestRegtechCollector::test_retry_mechanism", "type": "Function", "lineno": 253}, {"nodeid": "tests/test_collection_regtech.py::TestRegtechCollector::test_session_management", "type": "Function", "lineno": 280}, {"nodeid": "tests/test_collection_regtech.py::TestRegtechCollector::test_date_range_handling", "type": "Function", "lineno": 291}, {"nodeid": "tests/test_collection_regtech.py::TestRegtechCollector::test_data_transformation", "type": "Function", "lineno": 305}, {"nodeid": "tests/test_collection_regtech.py::TestRegtechCollector::test_error_recovery", "type": "Function", "lineno": 325}]}, {"nodeid": "tests/test_collection_regtech.py", "outcome": "passed", "result": [{"nodeid": "tests/test_collection_regtech.py::TestRegtechCollector", "type": "Class"}]}], "tests": [{"nodeid": "tests/test_collection_regtech.py::TestRegtechCollector::test_login_success", "lineno": 45, "outcome": "passed", "keywords": ["test_login_success", "__wrapped__", "patchings", "TestRegtechCollector", "test_collection_regtech.py", "tests/__init__.py", "blacklist"], "setup": {"duration": 0.001006349004455842, "outcome": "passed"}, "call": {"duration": 0.005439703003503382, "outcome": "passed"}, "teardown": {"duration": 0.0002727999963099137, "outcome": "passed"}}, {"nodeid": "tests/test_collection_regtech.py::TestRegtechCollector::test_login_failure", "lineno": 69, "outcome": "passed", "keywords": ["test_login_failure", "__wrapped__", "patchings", "TestRegtechCollector", "test_collection_regtech.py", "tests/__init__.py", "blacklist"], "setup": {"duration": 0.00043517899757716805, "outcome": "passed"}, "call": {"duration": 14.013445172997308, "outcome": "passed", "log": [{"name": "{__name__}.{name}", "msg": "\uc218\uc9d1 \uc624\ub958: {self.name} - {str(e)}", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/jclee/app/blacklist/src/core/collectors/unified_collector.py", "filename": "unified_collector.py", "module": "unified_collector", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 209, "funcName": "collect", "created": 1755426946.51965, "msecs": 519.0, "relativeCreated": 597.2874164581299, "thread": 128591517982720, "threadName": "MainThread", "processName": "MainProcess", "process": 1195178}, {"name": "{__name__}.{name}", "msg": "Traceback (most recent call last):\n  File \"/home/jclee/app/blacklist/src/core/collectors/unified_collector.py\", line 175, in collect\n    collected_data = await asyncio.wait_for(\n  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 445, in wait_for\n    return fut.result()\n  File \"/usr/lib/python3.10/unittest/mock.py\", line 2234, in _execute_mock_call\n    raise effect\nException: \ub85c\uadf8\uc778 \uc2e4\ud328 \ud6c4 \uc7ac\uc2dc\ub3c4 \ud55c\uacc4 \ub3c4\ub2ec\n", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/jclee/app/blacklist/src/core/collectors/unified_collector.py", "filename": "unified_collector.py", "module": "unified_collector", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 210, "funcName": "collect", "created": 1755426946.520407, "msecs": 520.0, "relativeCreated": 598.0443954467773, "thread": 128591517982720, "threadName": "MainThread", "processName": "MainProcess", "process": 1195178}, {"name": "{__name__}.{name}", "msg": "\uc218\uc9d1 \uc624\ub958: {self.name} - {str(e)}", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/jclee/app/blacklist/src/core/collectors/unified_collector.py", "filename": "unified_collector.py", "module": "unified_collector", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 209, "funcName": "collect", "created": 1755426948.5209131, "msecs": 520.0, "relativeCreated": 2598.55055809021, "thread": 128591517982720, "threadName": "MainThread", "processName": "MainProcess", "process": 1195178}, {"name": "{__name__}.{name}", "msg": "Traceback (most recent call last):\n  File \"/home/jclee/app/blacklist/src/core/collectors/unified_collector.py\", line 175, in collect\n    collected_data = await asyncio.wait_for(\n  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 445, in wait_for\n    return fut.result()\n  File \"/usr/lib/python3.10/unittest/mock.py\", line 2234, in _execute_mock_call\n    raise effect\n  File \"/home/jclee/app/blacklist/src/core/collectors/unified_collector.py\", line 175, in collect\n    collected_data = await asyncio.wait_for(\n  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 445, in wait_for\n    return fut.result()\n  File \"/usr/lib/python3.10/unittest/mock.py\", line 2234, in _execute_mock_call\n    raise effect\nException: \ub85c\uadf8\uc778 \uc2e4\ud328 \ud6c4 \uc7ac\uc2dc\ub3c4 \ud55c\uacc4 \ub3c4\ub2ec\n", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/jclee/app/blacklist/src/core/collectors/unified_collector.py", "filename": "unified_collector.py", "module": "unified_collector", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 210, "funcName": "collect", "created": 1755426948.5212543, "msecs": 521.0, "relativeCreated": 2598.8917350769043, "thread": 128591517982720, "threadName": "MainThread", "processName": "MainProcess", "process": 1195178}, {"name": "{__name__}.{name}", "msg": "\uc218\uc9d1 \uc624\ub958: {self.name} - {str(e)}", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/jclee/app/blacklist/src/core/collectors/unified_collector.py", "filename": "unified_collector.py", "module": "unified_collector", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 209, "funcName": "collect", "created": 1755426952.5222604, "msecs": 522.0, "relativeCreated": 6599.897861480713, "thread": 128591517982720, "threadName": "MainThread", "processName": "MainProcess", "process": 1195178}, {"name": "{__name__}.{name}", "msg": "Traceback (most recent call last):\n  File \"/home/jclee/app/blacklist/src/core/collectors/unified_collector.py\", line 175, in collect\n    collected_data = await asyncio.wait_for(\n  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 445, in wait_for\n    return fut.result()\n  File \"/usr/lib/python3.10/unittest/mock.py\", line 2234, in _execute_mock_call\n    raise effect\n  File \"/home/jclee/app/blacklist/src/core/collectors/unified_collector.py\", line 175, in collect\n    collected_data = await asyncio.wait_for(\n  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 445, in wait_for\n    return fut.result()\n  File \"/usr/lib/python3.10/unittest/mock.py\", line 2234, in _execute_mock_call\n    raise effect\n  File \"/home/jclee/app/blacklist/src/core/collectors/unified_collector.py\", line 175, in collect\n    collected_data = await asyncio.wait_for(\n  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 445, in wait_for\n    return fut.result()\n  File \"/usr/lib/python3.10/unittest/mock.py\", line 2234, in _execute_mock_call\n    raise effect\nException: \ub85c\uadf8\uc778 \uc2e4\ud328 \ud6c4 \uc7ac\uc2dc\ub3c4 \ud55c\uacc4 \ub3c4\ub2ec\n", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/jclee/app/blacklist/src/core/collectors/unified_collector.py", "filename": "unified_collector.py", "module": "unified_collector", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 210, "funcName": "collect", "created": 1755426952.5225573, "msecs": 522.0, "relativeCreated": 6600.194692611694, "thread": 128591517982720, "threadName": "MainThread", "processName": "MainProcess", "process": 1195178}, {"name": "{__name__}.{name}", "msg": "\uc218\uc9d1 \uc624\ub958: {self.name} - {str(e)}", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/jclee/app/blacklist/src/core/collectors/unified_collector.py", "filename": "unified_collector.py", "module": "unified_collector", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 209, "funcName": "collect", "created": 1755426960.5309556, "msecs": 530.0, "relativeCreated": 14608.592987060547, "thread": 128591517982720, "threadName": "MainThread", "processName": "MainProcess", "process": 1195178}, {"name": "{__name__}.{name}", "msg": "Traceback (most recent call last):\n  File \"/home/jclee/app/blacklist/src/core/collectors/unified_collector.py\", line 175, in collect\n    collected_data = await asyncio.wait_for(\n  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 445, in wait_for\n    return fut.result()\n  File \"/usr/lib/python3.10/unittest/mock.py\", line 2234, in _execute_mock_call\n    raise effect\n  File \"/home/jclee/app/blacklist/src/core/collectors/unified_collector.py\", line 175, in collect\n    collected_data = await asyncio.wait_for(\n  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 445, in wait_for\n    return fut.result()\n  File \"/usr/lib/python3.10/unittest/mock.py\", line 2234, in _execute_mock_call\n    raise effect\n  File \"/home/jclee/app/blacklist/src/core/collectors/unified_collector.py\", line 175, in collect\n    collected_data = await asyncio.wait_for(\n  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 445, in wait_for\n    return fut.result()\n  File \"/usr/lib/python3.10/unittest/mock.py\", line 2234, in _execute_mock_call\n    raise effect\n  File \"/home/jclee/app/blacklist/src/core/collectors/unified_collector.py\", line 175, in collect\n    collected_data = await asyncio.wait_for(\n  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 445, in wait_for\n    return fut.result()\n  File \"/usr/lib/python3.10/unittest/mock.py\", line 2234, in _execute_mock_call\n    raise effect\nException: \ub85c\uadf8\uc778 \uc2e4\ud328 \ud6c4 \uc7ac\uc2dc\ub3c4 \ud55c\uacc4 \ub3c4\ub2ec\n", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/jclee/app/blacklist/src/core/collectors/unified_collector.py", "filename": "unified_collector.py", "module": "unified_collector", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 210, "funcName": "collect", "created": 1755426960.5312526, "msecs": 531.0, "relativeCreated": 14608.890056610107, "thread": 128591517982720, "threadName": "MainThread", "processName": "MainProcess", "process": 1195178}]}, "teardown": {"duration": 0.00027465299353934824, "outcome": "passed"}}, {"nodeid": "tests/test_collection_regtech.py::TestRegtechCollector::test_data_collection_success", "lineno": 94, "outcome": "passed", "keywords": ["test_data_collection_success", "__wrapped__", "patchings", "TestRegtechCollector", "test_collection_regtech.py", "tests/__init__.py", "blacklist"], "setup": {"duration": 0.0004922489897580817, "outcome": "passed"}, "call": {"duration": 0.0026064609992317855, "outcome": "passed"}, "teardown": {"duration": 0.00023733198759146035, "outcome": "passed"}}, {"nodeid": "tests/test_collection_regtech.py::TestRegtechCollector::test_html_parsing", "lineno": 125, "outcome": "passed", "keywords": ["test_html_parsing", "TestRegtechCollector", "test_collection_regtech.py", "tests/__init__.py", "blacklist"], "setup": {"duration": 0.0004253009974490851, "outcome": "passed"}, "call": {"duration": 0.0005699169996660203, "outcome": "passed"}, "teardown": {"duration": 0.00020012199820484966, "outcome": "passed"}}, {"nodeid": "tests/test_collection_regtech.py::TestRegtechCollector::test_invalid_html_parsing", "lineno": 153, "outcome": "passed", "keywords": ["test_invalid_html_parsing", "TestRegtechCollector", "test_collection_regtech.py", "tests/__init__.py", "blacklist"], "setup": {"duration": 0.00041235699609387666, "outcome": "passed"}, "call": {"duration": 0.00021725401165895164, "outcome": "passed"}, "teardown": {"duration": 0.00019372999668121338, "outcome": "passed"}}, {"nodeid": "tests/test_collection_regtech.py::TestRegtechCollector::test_missing_table_elements", "lineno": 160, "outcome": "passed", "keywords": ["test_missing_table_elements", "TestRegtechCollector", "test_collection_regtech.py", "tests/__init__.py", "blacklist"], "setup": {"duration": 0.00036860299587715417, "outcome": "passed"}, "call": {"duration": 0.00046331400517374277, "outcome": "passed"}, "teardown": {"duration": 0.00018237699987366796, "outcome": "passed"}}, {"nodeid": "tests/test_collection_regtech.py::TestRegtechCollector::test_duplicate_removal", "lineno": 170, "outcome": "passed", "keywords": ["test_duplicate_removal", "TestRegtechCollector", "test_collection_regtech.py", "tests/__init__.py", "blacklist"], "setup": {"duration": 0.0003143189969705418, "outcome": "passed"}, "call": {"duration": 0.00023177199182100594, "outcome": "passed"}, "teardown": {"duration": 0.0001895220048027113, "outcome": "passed"}}, {"nodeid": "tests/test_collection_regtech.py::TestRegtechCollector::test_ip_address_validation", "lineno": 186, "outcome": "passed", "keywords": ["test_ip_address_validation", "TestRegtechCollector", "test_collection_regtech.py", "tests/__init__.py", "blacklist"], "setup": {"duration": 0.00036350300069898367, "outcome": "passed"}, "call": {"duration": 0.00023214299289975315, "outcome": "passed"}, "teardown": {"duration": 0.00019906899251509458, "outcome": "passed"}}, {"nodeid": "tests/test_collection_regtech.py::TestRegtechCollector::test_full_collection_process", "lineno": 203, "outcome": "passed", "keywords": ["test_full_collection_process", "__wrapped__", "patchings", "TestRegtechCollector", "test_collection_regtech.py", "tests/__init__.py", "blacklist"], "setup": {"duration": 0.00038798000605311245, "outcome": "passed"}, "call": {"duration": 0.0022503819927806035, "outcome": "passed"}, "teardown": {"duration": 0.00020280700118746608, "outcome": "passed"}}, {"nodeid": "tests/test_collection_regtech.py::TestRegtechCollector::test_error_handling_network_failure", "lineno": 237, "outcome": "passed", "keywords": ["test_error_handling_network_failure", "TestRegtechCollector", "test_collection_regtech.py", "tests/__init__.py", "blacklist"], "setup": {"duration": 0.0003712979960255325, "outcome": "passed"}, "call": {"duration": 14.016937531006988, "outcome": "passed", "log": [{"name": "{__name__}.{name}", "msg": "\uc218\uc9d1 \uc624\ub958: {self.name} - {str(e)}", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/jclee/app/blacklist/src/core/collectors/unified_collector.py", "filename": "unified_collector.py", "module": "unified_collector", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 209, "funcName": "collect", "created": 1755426960.5488083, "msecs": 548.0, "relativeCreated": 14626.445770263672, "thread": 128591517982720, "threadName": "MainThread", "processName": "MainProcess", "process": 1195178}, {"name": "{__name__}.{name}", "msg": "Traceback (most recent call last):\n  File \"/home/jclee/app/blacklist/src/core/collectors/unified_collector.py\", line 175, in collect\n    collected_data = await asyncio.wait_for(\n  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 445, in wait_for\n    return fut.result()\n  File \"/usr/lib/python3.10/unittest/mock.py\", line 2234, in _execute_mock_call\n    raise effect\nException: Network error\n", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/jclee/app/blacklist/src/core/collectors/unified_collector.py", "filename": "unified_collector.py", "module": "unified_collector", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 210, "funcName": "collect", "created": 1755426960.5489953, "msecs": 548.0, "relativeCreated": 14626.632690429688, "thread": 128591517982720, "threadName": "MainThread", "processName": "MainProcess", "process": 1195178}, {"name": "{__name__}.{name}", "msg": "\uc218\uc9d1 \uc624\ub958: {self.name} - {str(e)}", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/jclee/app/blacklist/src/core/collectors/unified_collector.py", "filename": "unified_collector.py", "module": "unified_collector", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 209, "funcName": "collect", "created": 1755426962.5513515, "msecs": 551.0, "relativeCreated": 16628.98898124695, "thread": 128591517982720, "threadName": "MainThread", "processName": "MainProcess", "process": 1195178}, {"name": "{__name__}.{name}", "msg": "Traceback (most recent call last):\n  File \"/home/jclee/app/blacklist/src/core/collectors/unified_collector.py\", line 175, in collect\n    collected_data = await asyncio.wait_for(\n  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 445, in wait_for\n    return fut.result()\n  File \"/usr/lib/python3.10/unittest/mock.py\", line 2234, in _execute_mock_call\n    raise effect\n  File \"/home/jclee/app/blacklist/src/core/collectors/unified_collector.py\", line 175, in collect\n    collected_data = await asyncio.wait_for(\n  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 445, in wait_for\n    return fut.result()\n  File \"/usr/lib/python3.10/unittest/mock.py\", line 2234, in _execute_mock_call\n    raise effect\nException: Network error\n", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/jclee/app/blacklist/src/core/collectors/unified_collector.py", "filename": "unified_collector.py", "module": "unified_collector", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 210, "funcName": "collect", "created": 1755426962.5516162, "msecs": 551.0, "relativeCreated": 16629.25362586975, "thread": 128591517982720, "threadName": "MainThread", "processName": "MainProcess", "process": 1195178}, {"name": "{__name__}.{name}", "msg": "\uc218\uc9d1 \uc624\ub958: {self.name} - {str(e)}", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/jclee/app/blacklist/src/core/collectors/unified_collector.py", "filename": "unified_collector.py", "module": "unified_collector", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 209, "funcName": "collect", "created": 1755426966.556007, "msecs": 556.0, "relativeCreated": 20633.644342422485, "thread": 128591517982720, "threadName": "MainThread", "processName": "MainProcess", "process": 1195178}, {"name": "{__name__}.{name}", "msg": "Traceback (most recent call last):\n  File \"/home/jclee/app/blacklist/src/core/collectors/unified_collector.py\", line 175, in collect\n    collected_data = await asyncio.wait_for(\n  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 445, in wait_for\n    return fut.result()\n  File \"/usr/lib/python3.10/unittest/mock.py\", line 2234, in _execute_mock_call\n    raise effect\n  File \"/home/jclee/app/blacklist/src/core/collectors/unified_collector.py\", line 175, in collect\n    collected_data = await asyncio.wait_for(\n  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 445, in wait_for\n    return fut.result()\n  File \"/usr/lib/python3.10/unittest/mock.py\", line 2234, in _execute_mock_call\n    raise effect\n  File \"/home/jclee/app/blacklist/src/core/collectors/unified_collector.py\", line 175, in collect\n    collected_data = await asyncio.wait_for(\n  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 445, in wait_for\n    return fut.result()\n  File \"/usr/lib/python3.10/unittest/mock.py\", line 2234, in _execute_mock_call\n    raise effect\nException: Network error\n", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/jclee/app/blacklist/src/core/collectors/unified_collector.py", "filename": "unified_collector.py", "module": "unified_collector", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 210, "funcName": "collect", "created": 1755426966.5562928, "msecs": 556.0, "relativeCreated": 20633.930206298828, "thread": 128591517982720, "threadName": "MainThread", "processName": "MainProcess", "process": 1195178}, {"name": "{__name__}.{name}", "msg": "\uc218\uc9d1 \uc624\ub958: {self.name} - {str(e)}", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/jclee/app/blacklist/src/core/collectors/unified_collector.py", "filename": "unified_collector.py", "module": "unified_collector", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 209, "funcName": "collect", "created": 1755426974.5642557, "msecs": 564.0, "relativeCreated": 28641.89314842224, "thread": 128591517982720, "threadName": "MainThread", "processName": "MainProcess", "process": 1195178}, {"name": "{__name__}.{name}", "msg": "Traceback (most recent call last):\n  File \"/home/jclee/app/blacklist/src/core/collectors/unified_collector.py\", line 175, in collect\n    collected_data = await asyncio.wait_for(\n  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 445, in wait_for\n    return fut.result()\n  File \"/usr/lib/python3.10/unittest/mock.py\", line 2234, in _execute_mock_call\n    raise effect\n  File \"/home/jclee/app/blacklist/src/core/collectors/unified_collector.py\", line 175, in collect\n    collected_data = await asyncio.wait_for(\n  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 445, in wait_for\n    return fut.result()\n  File \"/usr/lib/python3.10/unittest/mock.py\", line 2234, in _execute_mock_call\n    raise effect\n  File \"/home/jclee/app/blacklist/src/core/collectors/unified_collector.py\", line 175, in collect\n    collected_data = await asyncio.wait_for(\n  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 445, in wait_for\n    return fut.result()\n  File \"/usr/lib/python3.10/unittest/mock.py\", line 2234, in _execute_mock_call\n    raise effect\n  File \"/home/jclee/app/blacklist/src/core/collectors/unified_collector.py\", line 175, in collect\n    collected_data = await asyncio.wait_for(\n  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 445, in wait_for\n    return fut.result()\n  File \"/usr/lib/python3.10/unittest/mock.py\", line 2234, in _execute_mock_call\n    raise effect\nException: Network error\n", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/jclee/app/blacklist/src/core/collectors/unified_collector.py", "filename": "unified_collector.py", "module": "unified_collector", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 210, "funcName": "collect", "created": 1755426974.5645878, "msecs": 564.0, "relativeCreated": 28642.22526550293, "thread": 128591517982720, "threadName": "MainThread", "processName": "MainProcess", "process": 1195178}]}, "teardown": {"duration": 0.0002599760045995936, "outcome": "passed"}}, {"nodeid": "tests/test_collection_regtech.py::TestRegtechCollector::test_retry_mechanism", "lineno": 253, "outcome": "passed", "keywords": ["test_retry_mechanism", "TestRegtechCollector", "test_collection_regtech.py", "tests/__init__.py", "blacklist"], "setup": {"duration": 0.0004165440041106194, "outcome": "passed"}, "call": {"duration": 6.008060086998739, "outcome": "passed", "log": [{"name": "{__name__}.{name}", "msg": "\uc218\uc9d1 \uc624\ub958: {self.name} - {str(e)}", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/jclee/app/blacklist/src/core/collectors/unified_collector.py", "filename": "unified_collector.py", "module": "unified_collector", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 209, "funcName": "collect", "created": 1755426974.5675857, "msecs": 567.0, "relativeCreated": 28645.223140716553, "thread": 128591517982720, "threadName": "MainThread", "processName": "MainProcess", "process": 1195178}, {"name": "{__name__}.{name}", "msg": "Traceback (most recent call last):\n  File \"/home/jclee/app/blacklist/src/core/collectors/unified_collector.py\", line 175, in collect\n    collected_data = await asyncio.wait_for(\n  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 445, in wait_for\n    return fut.result()\n  File \"/usr/lib/python3.10/unittest/mock.py\", line 2247, in _execute_mock_call\n    result = effect(*args, **kwargs)\n  File \"/home/jclee/app/blacklist/tests/test_collection_regtech.py\", line 266, in failing_collect\n    raise Exception(f\"Failure {call_count}\")\nException: Failure 1\n", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/jclee/app/blacklist/src/core/collectors/unified_collector.py", "filename": "unified_collector.py", "module": "unified_collector", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 210, "funcName": "collect", "created": 1755426974.5678492, "msecs": 567.0, "relativeCreated": 28645.48659324646, "thread": 128591517982720, "threadName": "MainThread", "processName": "MainProcess", "process": 1195178}, {"name": "{__name__}.{name}", "msg": "\uc218\uc9d1 \uc624\ub958: {self.name} - {str(e)}", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/jclee/app/blacklist/src/core/collectors/unified_collector.py", "filename": "unified_collector.py", "module": "unified_collector", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 209, "funcName": "collect", "created": 1755426976.5702624, "msecs": 570.0, "relativeCreated": 30647.899866104126, "thread": 128591517982720, "threadName": "MainThread", "processName": "MainProcess", "process": 1195178}, {"name": "{__name__}.{name}", "msg": "Traceback (most recent call last):\n  File \"/home/jclee/app/blacklist/src/core/collectors/unified_collector.py\", line 175, in collect\n    collected_data = await asyncio.wait_for(\n  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 445, in wait_for\n    return fut.result()\n  File \"/usr/lib/python3.10/unittest/mock.py\", line 2247, in _execute_mock_call\n    result = effect(*args, **kwargs)\n  File \"/home/jclee/app/blacklist/tests/test_collection_regtech.py\", line 266, in failing_collect\n    raise Exception(f\"Failure {call_count}\")\nException: Failure 2\n", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/jclee/app/blacklist/src/core/collectors/unified_collector.py", "filename": "unified_collector.py", "module": "unified_collector", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 210, "funcName": "collect", "created": 1755426976.5705688, "msecs": 570.0, "relativeCreated": 30648.20623397827, "thread": 128591517982720, "threadName": "MainThread", "processName": "MainProcess", "process": 1195178}]}, "teardown": {"duration": 0.00029816800088156015, "outcome": "passed"}}, {"nodeid": "tests/test_collection_regtech.py::TestRegtechCollector::test_session_management", "lineno": 280, "outcome": "passed", "keywords": ["test_session_management", "TestRegtechCollector", "test_collection_regtech.py", "tests/__init__.py", "blacklist"], "setup": {"duration": 0.0004688140033977106, "outcome": "passed"}, "call": {"duration": 0.000810867000836879, "outcome": "passed"}, "teardown": {"duration": 0.00021270599972922355, "outcome": "passed"}}, {"nodeid": "tests/test_collection_regtech.py::TestRegtechCollector::test_date_range_handling", "lineno": 291, "outcome": "passed", "keywords": ["test_date_range_handling", "TestRegtechCollector", "test_collection_regtech.py", "tests/__init__.py", "blacklist"], "setup": {"duration": 0.0003627019905252382, "outcome": "passed"}, "call": {"duration": 0.00019859799067489803, "outcome": "passed"}, "teardown": {"duration": 0.00019850900571327657, "outcome": "passed"}}, {"nodeid": "tests/test_collection_regtech.py::TestRegtechCollector::test_data_transformation", "lineno": 305, "outcome": "passed", "keywords": ["test_data_transformation", "TestRegtechCollector", "test_collection_regtech.py", "tests/__init__.py", "blacklist"], "setup": {"duration": 0.0003405390016268939, "outcome": "passed"}, "call": {"duration": 0.0014249770028982311, "outcome": "passed"}, "teardown": {"duration": 0.00020213599782437086, "outcome": "passed"}}, {"nodeid": "tests/test_collection_regtech.py::TestRegtechCollector::test_error_recovery", "lineno": 325, "outcome": "passed", "keywords": ["test_error_recovery", "TestRegtechCollector", "test_collection_regtech.py", "tests/__init__.py", "blacklist"], "setup": {"duration": 0.00039027399907354265, "outcome": "passed"}, "call": {"duration": 2.0035623040021164, "outcome": "passed", "log": [{"name": "{__name__}.{name}", "msg": "\uc218\uc9d1 \uc624\ub958: {self.name} - {str(e)}", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/jclee/app/blacklist/src/core/collectors/unified_collector.py", "filename": "unified_collector.py", "module": "unified_collector", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 209, "funcName": "collect", "created": 1755426980.5833027, "msecs": 583.0, "relativeCreated": 34660.940170288086, "thread": 128591517982720, "threadName": "MainThread", "processName": "MainProcess", "process": 1195178}, {"name": "{__name__}.{name}", "msg": "Traceback (most recent call last):\n  File \"/home/jclee/app/blacklist/src/core/collectors/unified_collector.py\", line 175, in collect\n    collected_data = await asyncio.wait_for(\n  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 445, in wait_for\n    return fut.result()\n  File \"/usr/lib/python3.10/unittest/mock.py\", line 2247, in _execute_mock_call\n    result = effect(*args, **kwargs)\n  File \"/home/jclee/app/blacklist/tests/test_collection_regtech.py\", line 337, in intermittent_failure\n    raise Exception(\"Temporary failure\")\nException: Temporary failure\n", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/jclee/app/blacklist/src/core/collectors/unified_collector.py", "filename": "unified_collector.py", "module": "unified_collector", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 210, "funcName": "collect", "created": 1755426980.583495, "msecs": 583.0, "relativeCreated": 34661.13233566284, "thread": 128591517982720, "threadName": "MainThread", "processName": "MainProcess", "process": 1195178}]}, "teardown": {"duration": 0.0015155209985096008, "outcome": "passed"}}]}